name: Test
on: push

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: sudo apt update && sudo apt-get install qemu-system-aarch64
      - name: Build
        run: make
      - name: Extra print Test
        run: python ./scripts/grade-lab1-extra.py
      - name: All Test
        run: make grade
